#version: '3.8'

services:
    uncademy_acadrec_ms:
      container_name: UNcademy_acadRec_ms
      build: ./UNcademy_acadRec_ms
      ports: 
        - 8000:8000
      depends_on:
        - uncademy_acadrec_db

    uncademy_acadrec_db:
      container_name: UNcademy_acadRec_db 
      image: mongo
      ports:
        - 27018:27017

