#version: '3.8'

services:
  app:
    build: ./UNcademy_acadRec_ms
    ports: 
      - 3333:8000
    environment:
      - DB_URL=mongodb://db:27017/
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27088:27017

