#version: '3.8'

services:

  app:
    build: ./UNcademy_acadRec_ms
    ports: 
      - 3333:8000
    environment:
      - DB_URL=mongodb://db:27017/
      - MQ_URL=172.17.0.1
#      - MQ_URL=amqp://guest:guest@rabbitmq/
    depends_on:
      - db
#  rabbitmq:
#      image: rabbitmq
  db:
    image: mongo
    ports:
      - 27088:27017

